config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  resources :students do
    resources :addresses
  end
end

app/models/address.rb
class Address < ApplicationRecord
  validates :description, presence: true
  validates :street_address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip_code, presence: true

  belongs_to :student
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
  validates :name, presence: true

  has_many :addresses
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def new
    @student = Student.find(params[:student_id])
    @address = @student.addresses.new()
  end

  def create
    @student = Student.find(params[:student_id])
    @address = @student.addresses.new(address_params)
    if @address.save
      redirect_to student_path(@student)
    else
      render :new
    end
  end

  private

  def address_params
    params.require(:address).permit(:description, :street_address, :city, :state, :zip_code)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new()
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to student_path(@student)
    else
      render :new
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    if @student.update(student_params)
      redirect_to student_path(@student)
    else
      render :edit
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to students_path
  end

  private

  def student_params
    params.require(:student).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/_form.html.erb
<%= form_for [@student, @address] do |f| %>
  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :street_address %>
  <%= f.text_field :street_address %>

  <%= f.label :city %>
  <%= f.text_field :city %>

  <%= f.label :state %>
  <%= f.text_field :state %>

  <%= f.label :zip_code %>
  <%= f.text_field :zip_code %>

  <%= f.submit %>
<% end %>

app/views/addresses/new.html.erb
<h1>Add a new student address here</h1>

<%= render partial: "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Enrollment</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_for @student do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  
  <%= f.submit %>
<% end %>

app/views/students/_nav.html.erb
<%= link_to 'See All Students', students_path %>
<br/>

<%= link_to 'Create a New Student', new_student_path %>

app/views/students/edit.html.erb
<%= render partial: "nav" %>

<h1>Edit a student's information</h1>

<%= render partial: "form" %>

app/views/students/index.html.erb
<%= render partial: "nav" %>

<h1>This is a list of all students</h1>

<% @students.each do |student| %>
  <p> <%= link_to student.name, student_path(student) %> - <%= link_to "Delete", student_path(student), method: "delete" %> </p>
<% end %>

app/views/students/new.html.erb
<%= render partial: "nav" %>

<h1>Create a student here:</h1>

<%= render partial: "form" %>

app/views/students/show.html.erb
<%= render partial: "nav" %>

<h1>Student Information:</h1>

<%= @student.name %>

<br>

<% @student.addresses.each do |address| %>
  <%= address.description %>
  <%= address.street_address %>,
  <%= address.city %>,
  <%= address.state %>
  <%= address.zip_code %>
<% end %>

<%= link_to 'Edit Student', edit_student_path(@student) %>